configcat/go-sdk

- auto_polling_policy.go
- auto_polling_policy_test.go
- config_cache.go
- config_fetcher.go
- configcat_client.go
- lazy_loading_policy.go
- lazy_loading_policy_test.go
- logger.go
- manual_polling_policy_test.go
It's a bit frustrating to have a library spewing unstructured logs into stderr without having any control over it - this PR changes the client configuration to accept an `interface Logger`, which allows the implementer to spawn child loggers from a parent logger as is standard practice with things like [`zap.Named`](https://godoc.org/go.uber.org/zap#Logger.Named). The default implementation simply spawns new loggers with `log.New`
Happy to make adjustments if needed!
> abstract logger behind pluggable interface

- rollout_evaluator.go
- user.go
This PR changes `getAttribute` to a public method.
This can be usefull to get information about the `User` you had just initialized.
> Exchanging *User getAttribute to public method.

- v6/config_fetcher.go
- v6/config_parser.go
- v6/constants.go
- v6/rollout_evaluator.go
The Go encoding/json package makes it easy to define types
that represent the shape of the expected data, which lets the
JSON parser do most of the heavy lifting around checking for
type compatibility.
This PR changes the code to follow this approach, arguably
making the code cleaner and  easier to follow.
Also define an `operator` type which is idiomatic in Go for representing
a known set of constants, rather than using literal numbers in the codee.
> v6: use less dynamic JSON parsing

- v6/configcat_client.go
Factor out some of the repeated common logic for getting the config
synchronously into a method used by all the synchronous Client methods.
> v6: simplify client logic

- v6/auto_polling_policy.go
- v6/lazy_loading_policy.go
- v6/manual_polling_policy.go
This makes it the division of responsibilities a little bit clearer
between the `configRefresher` type and the individual policy
implementations in preparation for some later refactoring of
the async refresh logic.
> v6: use less embedding in policy implementations

- v6/auto_polling_policy.go
- v6/lazy_loading_policy.go
- v6/manual_polling_policy.go
- v6/refresh_policy.go
Also avoid embedding the mutex (it's not idiomatic to do that,
as the mutex is generally considered to be a private
implementation detail of the type), and position it in the
struct so that it's more clear which fields it's guarding.
Also acquire the read lock inside `getLastCachedConfig`.
> v6: return pointer fron newConfigRefresher

- v6/auto_polling_policy.go
- v6/config_fetcher.go
- v6/config_parser.go
- v6/config_parser_test.go
- v6/configcat_client.go
- v6/configcat_client_test.go
- v6/configserver_test.go
- v6/eval.go
- v6/logger.go
- v6/rollout_integration_test.go
- v6/user.go
v6: restore missed logging messages
There were a few informational and warning messages that had
been missed in the transition. We reinstate those, but they
made things slower again, so we add  wrapper type
that can be used to inspect the logging level before logging,
which avoids the allocations from calling the log methods.
Also change the log level type to be an alias to the logrus
level type so that we can define the `LoggerWithLevel` interface
without needing to use two level types in the public API.
This should be backwardly compatible except for some
highly unlikely (and easily fixable) use cases, such as `fmt.Sprint(level)`
formatting differently because `logrus.Level` implements a `String` method.
We also use a more realistic benchmark that actually
exercises the rules by passing …
> v6: restore missed logging messages

- v6/benchmark_test.go
- v6/configserver_test.go
- v6/rollout_integration_test.go
Add some more benchmarks so that we
can compare costs with v7.
Note that the `Get/with-percentage` benchmark
is exactly the same as the old `GetValue` benchmark
except that it also includes creation of the user value
as part of the benchmark.
```
name                      time/op
Get/one-of-8              314ns ± 0%
Get/less-than-with-int-8  403ns ± 2%
Get/with-percentage-8     635ns ±14%
name                      alloc/op
Get/one-of-8               360B ± 0%
Get/less-than-with-int-8   360B ± 0%
Get/with-percentage-8      456B ± 0%
name                      allocs/op
Get/one-of-8               3.00 ± 0%
Get/less-than-with-int-8   3.00 ± 0%
Get/with-percentage-8      5.00 ± 0%
```
> v6: more benchmarks

- v7/benchmark_test.go
- v7/config_parser.go
- v7/configcat_client.go
- v7/configcat_client_test.go
- v7/configserver_test.go
- v7/eval.go
- v7/eval_test.go
- v7/rollout_integration_test.go
- v7/user.go
- v7/visiblefields.go
This allows a user-defined User object to be passed in,
making it easier to use an arbitrary domain object for the
user data and avoiding the need to convert to and from the
intermediate string format for numeric comparisons.
Although the specification is simple (allow any numeric type or any
type with a String method), that allows for quite a number of possible
combinations, so the eval code becomes somewhat more complex.
It might be better to restrict the number of possible types
(for example, by only allowing `int` and `float64` and `string`)
or use floating point comparisons always for the numeric operators,
which might reduce the amount of code required.
I can't quite decide!
Benchmarks compared with v6:
```
name                      old time/op    new time/op    delta
Get/one-of-8 …
```
> v7: reflection-based API

- v7/config_parser.go
- v7/configcat_client.go
- v7/configcat_client_test.go
- v7/flag.go
- v7/lazy_loading_policy_test.go
- v7/snapshot.go
We can use the settingType (`t`) value in the config
to know what kind of value should be returned.
> v7: add generic value-get methods

- v7/snapshot.go
- v7/snapshot_test.go
If a nil snapshot is used (for example because a snapshot
wasn't attached to a context as expected), it's nice to
ignore the panic and treat it like any other "configuration
not available" situation, so make nil snapshots usable.
> v7: avoid panic when nil snapshot is used

- v7/config_parser.go
`go vet` was complaining (with good reason) about the copy of the
configuration that `withFetchTime` does. Avoid the error by
using a `*sync.Map` instead of `sync.Map` directly.
Another possible solution would be to avoid putting the
fetch time inside the configuration, but it seems like that
would make the rest of the code more complex for not much gain.
> v7: avoid copying mutex when copying configuration

- v7/configcat_client.go
When the clock resolution is coarse, the most recently retrieved
configuration might still be at the current time, so ensure that can't happen.
> v7: always refresh when asked

- v7/configserver_test.go
- v7/eval.go
- v7/eval_test.go
- v7/rollout_integration_test.go
- v7/snapshot_test.go
After the PR feedback on https://github.com/configcat/go-sdk/pull/41,
I realised that a significant current issue is the lack of tests for
the expected logging output, meaning that it's easy to change
code such that the logged output changes without breaking tests.
This PR adds some tests for logs.
We can see that some improvement could be made - for example
none of the logs mention what key is currently being evaluated - but
we'll leave that for another PR.
> v7: add tests for log output

- v7/benchmark_test.go
- v7/config_parser.go
- v7/configcat_client.go
- v7/configserver_test.go
- v7/eval.go
- v7/logger.go
- v7/snapshot.go
- v7/snapshot_test.go
Rather than creating a fake configuration just for the static snapshot,
we can just create the evaluators directly, which means that we can
do the creation faster and in O(1) allocations.
There's a small amount of performance regression in the other benchmarks,
but nothing really significant IMHO.
```
name                                   old time/op    new time/op    delta
Get/one-of/get-and-make-8                 272ns ± 0%     295ns ± 9%   +8.50%  (p=0.008 n=5+5)
Get/one-of/get-only-8                    53.4ns ± 0%    59.2ns ± 4%  +10.92%  (p=0.008 n=5+5)
Get/less-than-with-int/get-and-make-8     194ns ± 4%     209ns ± 1%   +7.24%  (p=0.008 n=5+5)
Get/less-than-with-int/get-only-8        22.6ns ± 0%    23.0ns ± 0%   +1.60%  (p=0.008 n=5+5)
Get/with-percentage/get-and-make-8 …
```
> v7: more efficient NewSnapshot

- v7/benchmark_test.go
- v7/config_fetcher.go
- v7/config_parser.go
- v7/configcat_client_test.go
- v7/eval.go
- v7/eval_test.go
- v7/internal/wireconfig/wireconfig.go
- v7/lazy_loading_policy_test.go
- v7/snapshot_test.go
As a preparatory step for a `fakeconfigcat` package, this
PR factors out the relevant wire structs into their own
package so that they can be imported without the
need to expose them in the public API.
The changes were made automatically by running
the following [rf](https://rsc.io/rf) command:
```
rf '
mv rootNode RootNode
mv entryType EntryType
mv preferences Preferences
mv percentageRule PercentageRule
mv operator Operator
mv redirectionKind RedirectionKind
mv rolloutRule RolloutRule
mv entry Entry
mv boolEntry BoolEntry
mv stringEntry  StringEntry
mv intEntry IntEntry
mv floatEntry FloatEntry
mv opOneOf OpOneOf
mv opNotOneOf OpNotOneOf
mv opContains OpContains
mv opNotContains OpNotContains
mv opOneOfSemver OpOneOfSemver
mv opNotOneOfSemver OpNotOneOfSemver
mv opLessSemver …
```
> v7: factor out internal/wireconfig package

- v7/configcattest/doc.go
- v7/configcattest/flag.go
- v7/configcattest/handler.go
- v7/configcattest/handler_test.go
- v7/configcattest/operator.go
- v7/internal/wireconfig/wireconfig.go
This makes it simple to set up a fake configcat server for testing purposes.
> configcat/configcattest: new package

- v7/benchmark_test.go
- v7/internal/wireconfig/wireconfig.go
- v7/rollout_integration_test.go
- v7/snapshot_test.go
In preparation for the performance improvements in #46,
this PR updates the tests to test more aspects of the implementation.
One notable change is that the type of the "expected" value in the integration
tests is no longer derived from the value received by the implementation.
Unfortunately the test data does not specifically say what type is
expected, but in practice it's always specific enough that we can
determine the type (in particular floating point numbers always have
a decimal point and booleans are always formatted as `True` or `False`.
This change exposed an issue with the percentage rule value fixup which
meant that the values weren't being updated, which is now fixed.
> v7: better tests

- v7/benchmark_test.go
- v7/config_fetcher.go
- v7/config_parser.go
- v7/eval.go
- v7/internal/wireconfig/wireconfig.go
- v7/rollout_integration_test.go
- v7/snapshot.go
- v7/snapshot_test.go
- v7/user.go
This optimization means that complex rules will only be evaluated once
for any given config/user combination - the previous result is used when
possible.
We also make it clear that a User value is intended to be unchanging,
and fix an issue with int-values in percentage rules where they
could return a float64 instead of an int.
Any values that can be computed when the configuration is parsed
are stored then; any that cannot are stored in a slice, created on demand,
that's only as large as it needs to be, and only on demand, which means
that in the common case where the only flags inspected have no rollout
rules, this will be quite efficient.
As a special case when the configuration is parsed, we also compute
the snapshot for the no-user case. This is particularly helpful for long-running …
> v7: evaluate any rule at most once

- v7/flag.go
This means that there's a common API for all flags
that can be used to get a flag's value as an interface.
This is technically unnecessary - a caller could use
`Snapshot.GetValue` - but using `Flag.GetValue` means
the you get to use the flag's default and the precalculated
key id that's inside the flag, which makes it more efficient.
This gives a few ns of penalty in the lowrer-cost benchmarks,
but nothing to worry about IMHO - 10ns for a call is still pretty good :)
```
name                                   old time/op    new time/op    delta
Get/one-of/get-and-make-8                 241ns ± 1%     242ns ± 3%     ~     (p=0.841 n=5+5)
Get/one-of/get-only-8                    7.40ns ± 1%    9.31ns ± 0%  +25.86%  (p=0.008 n=5+5)
Get/less-than-with-int/get-and-make-8     204ns ±11% …
```
> v7: implement GetValue method on flags

- v7/benchmark_test.go
- v7/config_fetcher.go
- v7/config_parser.go
- v7/configcat_client.go
- v7/configcat_client_test.go
- v7/snapshot.go
Currently we optimize for the special case where there's no
user info, which considerably improves performance when
making queries when there's no current request. However
this optimization doesn't help when there are some global
attributes that are associated with all feature flag requests,
even when there's no current request context. For example,
we might want to target feature flag values based on the current
environment or machine.
This PR introduces a `DefaultUser` field to the configuration,
giving "user" information that is used whenever there's no
explicit reques, bringing the performance in this case up to
the same level as the original "no user" case.
```
name                                   old time/op    new time/op    delta
Get/one-of/get-and-make-8                 193ns ± …
```
> v7: add Config.DefaultUser

- v7/configcattest/flag.go
- v7/configcattest/handler.go
The v6 feature flag logic ignores rules when they don't
have a variation ID, so include an arbitrary variation ID
so that it the configcattest server works for tests against
that client too.
> v7/configcattest: add variation IDs

- v7/configcat_client_test.go
- v7/snapshot.go
This PR fixes an oversight that when there are empty slots
in the configuration's precalculated value slice, the
logic didn't check for that and instead tried to use the zero
value as a bad cache index, leading to a panic.
> fix: v7: fix panic when key isn't found

- v7/config_fetcher.go
- v7/config_parser.go
- v7/configcat_client.go
- v7/flag.go
- v7/flag_overrides.go
- v7/flag_overrides_test.go
- v7/policy_test.go
This PR makes a few changes to the logic proposed in PR #52,
some of which were a bit hard to suggest as comments, hence
I'm proposing them as code. Note the target of this PR (not master!).
- rename `Behaviour` to `Behavior` (US spelling is standard in Go)
- simplify the override parser so that it's only concerned with creating a set of entries, and not with creating a snapshot.
- use the regular config fetcher even in local-only mode (this also makes it easier for us to
add polling for the local override file changing in the future if we want)
> suggested amendments to overrides logic

- .github/workflows/go-ci.yml
- resources/local-simple.json
- resources/local.json
- samples/console/main.go
- v7/config_fetcher.go
- v7/config_parser.go
- v7/configcat_client.go
- v7/configcat_client_test.go
- v7/flag.go
- v7/flag_overrides.go
- v7/flag_overrides_test.go
- v7/internal/wireconfig/wireconfig.go
- v7/policy_test.go
- v7/snapshot.go
- v7/version.go
This PR applies the following:
- A `GetAllValues()` function that evaluates all flags & settings in a `map[string]interface{}`.
- New `FlagOverrides` configuration option to support the reading of flags & settings from a local file or from a `map[string]interface{}`.
> Add flag overrides and GetAllValues() function

- v7/configcat_client.go
- v7/flag.go
- v7/flag_overrides.go
- v7/flag_overrides_test.go
- v7/snapshot.go
- avoid checking for nil fetcher (it's always present)
- set types of entries even when reading override config from full file (making it easier for people to make a valid config file)
- add a couple of tests to check the edge-case behaviour of int vs float when overriding
- simplify `Snapshot.GetAllValues`
- doc tweaks
> v7: minor tweaks to override code

- v7/configcat_client_test.go
- v7/snapshot.go
The following exposes the underlying config fetchTime so it's possible to
know when a given snapshot was taken. As snapshots act like readonly
encapsulations around configs, it's important to know if they're up to
date or not.
N/A
> feat(snapshot): Expose config FetchTime for snapshots
